version: '3.8'
services:
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_USER=yasar
      - POSTGRES_PASSWORD=123
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5431:5432'
volumes:
  postgres: